name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up BellSoft JDK 21
        uses: sdkman/sdkman-action@master
        with:
          candidate: java
          version: 21.0.4.9.bellsoft

      - name: Cache Maven local repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and Allure
        run: |
          sudo apt-get update && sudo apt-get install -y netcat unzip curl
          curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip allure-2.27.0.zip -d allure-bin
          echo "$GITHUB_WORKSPACE/allure-bin/allure-2.27.0/bin" >> $GITHUB_PATH

      - name: Build application
        run: mvn -f pom.xml clean package

      - name: Start app and wait for it
        run: |
          java -jar target/qa-cucumber-example-1.0-SNAPSHOT.jar &
          ./wait-for-it.sh localhost:8080 -t 60 -- echo "? Сервис доступен!"

      - name: Run autotests
        run: mvn -f autotests/pom.xml clean test

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: autotests/target/allure-results

  allure-report:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: autotests/target/allure-results

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip allure-2.27.0.zip -d allure-bin

      - name: Generate Allure report
        run: |
          allure-bin/allure-2.27.0/bin/allure generate autotests/target/allure-results --clean -o autotests/target/allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: autotests/target/allure-report
